#
# KorRPC dispatcher daemon configuration
#

#-----------------------------------------------------------------------------
# network configuration

# ports and addresses to listen on [list of strings "address:port"]
listen = ["*:3502"]

#-----------------------------------------------------------------------------
# jobs

# where to store jobs' results
stream_directory = "/var/lib/korrpcdid/stream/"

# default timeout for any single read activity (either a result or a record of
# job's stream output) [seconds]
default_timeout = 600

# maximum time that job is allowed to take; after this time, the job is
# terminated [seconds]
max_exec_time = 600

# file with all recognized CAs; if not defined, no CA checking will be
# performed when connecting to client
#ca_file = "/etc/ssl/certs/ca-certificates.crt"
# file with all recognized client certificates (may not exist)
# TODO: define meaning of the file
known_certs_file = "/etc/korrpcdid/known_certs.pem"

#-----------------------------------------------------------------------------
# hosts registry parameters

# script to update hosts registry
# expected script's output: JSON lines of following form:
#   {"hostname": "localhost", "address": "127.0.0.1", "port": 3505, "credentials": {"user": "name", "password": "secret"}}
host_db_script = "/etc/korrpcdid/update-hosts"

# file to cache hosts registry
host_db = "/var/lib/korrpcdid/hosts.db"

# how often the hosts registry will be refreshed [seconds]
host_db_refresh = 900

#-----------------------------------------------------------------------------
# logging

# list of log handlers for logs from KorRPC dispatcher
# prepared handlers: korrpcdid_syslog_h, korrpcdid_stdout_h
log_handlers = ["korrpcdid_syslog_h"]

#-----------------------------------------------------------------------------
# Erlang configuration

[erlang]

# name of Erlang node in distributed mode (<node_name>@<hostname>)
node_name = "korrpcdid"
# type of hostnames in distributed mode ("longnames" or "shortnames", as
# net_kernel documentation says)
name_type = "longnames"
# text file with magic cookie to use in distributed Erlang
cookie_file = "/etc/korrpcdid/cookie.txt"
# start distributed Erlang immediately or on command-line request
# ("korrpcdid dist-erl-start")
distributed_immediate = false

# event handlers for error_logger (Erlang system events) to add when starting
error_logger_handlers = []

# vim:ft=dosini
