version: 1
root:
  level: NOTSET    # optional; DEBUG, INFO, WARNING, ERROR, CRITICAL, NOTSET
  #filters: [...]  # optional
  handlers: [stderr]
formatters:
  terse:
    format: "%(message)s"
  timestamped:
    format: "%(asctime)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  stderr:
    class: logging.StreamHandler
    formatter: terse
    #level: CRITICAL
    #filters: [...]
    stream: ext://sys.stderr
